> 关键词：线性代数 / 矩阵 / 行列式

矩阵作为绝大多数算法的算子，当矩阵里的数字被赋予了意义，例如每个 row 表示了一个线性方程式，那么如果把这些线性方程用向量的形式在 xyz 空间坐标中表示，从几何角度解释的话，行列式值就可以是这些向量所夹出的一个平行四边形面积，或者平行六面体的体积，甚至是一些更高维度没办法具体表但又类似前两者的一个抽象概念。这回小编要用 Python 的视角重新帮大家复习一下行列式的基本定义，并且用代码来证明行列式计算过程中的重要性质！

In [1]:
import numpy as np

# 行列式 Determinant
若 A 为 n 阶方阵，如下定义：

$$
A = 
\begin{bmatrix} a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
                a_{21} & a_{22} & a_{23} & \cdots & a_{2n} \\
                ...  & ...  & ...  & \quad  & ... \\
                a_{n1} & a_{n2} & a_{n3} & \cdots & a_{nn}\end{bmatrix}
= \big[a_{ij}\big]
$$

A 的行列式值则为：

$$
|A| = 
\begin{vmatrix} a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
                a_{21} & a_{22} & a_{23} & \cdots & a_{2n} \\
                ...  & ...  & ...  & \quad  & ... \\
                a_{n1} & a_{n2} & a_{n3} & \cdots & a_{nn}\end{vmatrix}
= det(A)
$$

In [2]:
A = np.random.randint(0, 9, 9).reshape(3, 3)
A

array([[1, 5, 6],
       [4, 0, 0],
       [0, 0, 6]])

In [3]:
np.linalg.det(A)

-119.99999999999997

p.s. 注意只有方阵才能计算行列式值，否则程序报错。

In [4]:
B = np.random.randint(0, 6, 12).reshape(4, 3)
B

array([[5, 2, 0],
       [0, 3, 4],
       [3, 2, 1],
       [1, 3, 4]])

In [5]:
np.linalg.det(B)

LinAlgError: Last 2 dimensions of the array must be square

## 1. 子行列式 - Minor
若将 A 方阵中的第 i 列与第 j 行删除，所剩下的 n-1 阶方阵的行列式，称为元素 $a_{ij}$ 的子行列式，以 $M_{ij}$ 表示。

In [6]:
def minor(mat, row=1, col=1):
    mat = np.delete(mat, row, axis=0)
    mat = np.delete(mat, col, axis=1)
    return mat

In [7]:
minor(A, 0, 0)

array([[0, 0],
       [0, 6]])

In [8]:
minor(A, 1, 0)

array([[5, 6],
       [0, 6]])

In [9]:
np.linalg.det(minor(A, 1, 0))

29.99999999999999

## 2. 余因式 - cofactor
在行列式中元素 $a_{ij}$ 的余因式定义为：$\rightarrow C_{ij} = (-1)^{i+j}M_{ij}$

In [10]:
def cofactor(mat, row, col):
    val = np.linalg.det(minor(mat, row, col))
    return ((-1) ** (row + col)) * val

In [11]:
cofactor(A, 0, 0)

0.0

In [12]:
cofactor(A, 1, 0)

-29.99999999999999

## 3. 行列式展开
$$\begin{align}
det(A) = |A| &= \sum_{i=1}^na_{ij}c_{ij}\quad (对第j行展开)
\\
&= \sum_{j=1}^na_{ij}c_{ij}\quad (对第i列展开)
\end{align}$$

1. 某元素与该元素余因式 (cofactor) 的乘积和为行列式值
2. 行列式值可由任一列 (row) 展开求的
3. 行列式值可由任一行 (column) 展开求的

In [13]:
def determinant(mat):
    val = 0
    for i in range(mat.shape[0]):
        val += mat[i, 0] * cofactor(mat, i, 0)
        
    # for j in range(mat.shape[1]):
    #     val += mat[0, j] * cofactor(mat, 0, j)

    return val

In [14]:
determinant(A)

-119.99999999999996

In [15]:
np.linalg.det(A)

-119.99999999999997

## 4. 行列式基本性质
### 4-1
若行列式中有某一列 or 行 的元素全为 0，则行列式值为 0。

In [16]:
determinant(np.array([[0, 0, 0],
                      [2, 8, 4],
                      [5, 5, 9]]))

0.0

### 4-2
若行列式中有某一列 or 行 的元素都乘以 k 倍，则行列式值为原行列式的 k 倍。

### 4-3
若方阵 A 的行列式乘以 k 倍，可把 k 放到任意列 or 行中。

In [17]:
A[:, 2] = A[:, 2] * 5
determinant(A)

-599.9999999999999

### 4-4
若方阵为上三角 or 下三角矩阵，则该矩阵的行列式值为主对角元素的乘积。

In [18]:
determinant(np.triu(A))

0.0

In [19]:
determinant(np.tril(A))

0.0

### 4-5
若方阵中的任意两列 or 行互换位置，则相对应的行列式值为相反数 (差一个负号)。

In [20]:
from copy import copy
c = copy(A[0, :])
A[0, :] = A[1, :]
A[1, :] = c
determinant(A)

599.9999999999999

### 4-6
若方阵中任意两列 or 行的元素皆相同，则行列式值为零

In [21]:
determinant(np.array([[1, 2, 3],
                      [1, 2, 3],
                      [7, 8, 5]]))

0.0

### 4-7
若方阵任意两列 or 行的元素成比例，则行列式值为零

In [22]:
determinant(np.array([[1, 2, 3],
                      [2, 4, 6],
                      [7, 10, 9]]))

-3.552713678800501e-15

### 4-8
若 A 与 B 两方阵中除了第 k 列 or 行之外，其他列 or 行的元素皆相同，且 D 方阵中除了第 k 列 or 行为 A 与 B 两方阵第 k 列 or 行的元素和，并且其他元素皆与 A 和 B 相同时，则: $\rightarrow |D| = |A| + |B|$

$$
\begin{vmatrix}
  a &   b &   c \\
b+c & c+a & a+b \\
a-b & b-c & c-a 
\end{vmatrix} = \begin{vmatrix}
                      a &   b &   c \\
                      b &   c &   a \\
                    a-b & b-c & c-a
                \end{vmatrix} + \begin{vmatrix}
                                    a &   b &   c \\
                                    c &   a &   b \\
                                  a-b & b-c & c-a
                                \end{vmatrix}
$$

### 4-9
A 方阵中的第 i 列 or 行乘以 k 倍后，加到第 j 列 or 行中得到的新方阵，行列式值仍然为 |A|。

In [23]:
from copy import copy
c = copy(A[0, :])
A[0, :] += A[1, :] * 10    # k = 10 in this case.
determinant(A)

599.9999999999995

### 4-10
方阵 A 的行列式值与其转置矩阵的行列式值相同。

In [24]:
determinant(A), determinant(A.T)

(599.9999999999995, 599.9999999999993)

### 4-11
若 A 与 B 皆为 n 阶方阵，则 $|AB| = |A| + |B|$

In [25]:
C = np.random.randint(1, 9, 9).reshape(3, 3)
D = np.random.randint(1, 9, 9).reshape(3, 3)
determinant(np.dot(C, D))

8568.000000000407

In [26]:
determinant(C) * determinant(D)

8568.000000000002

### 4-12
若 A 为 n 阶方阵，k 为常数，则 $|kA| = k^n|A|$。

In [27]:
determinant(2 * A)

4800.000000000009

In [28]:
(2 ** A.shape[0]) * determinant(A)

4799.999999999996

### 4-13
若 A 为 n 阶方阵，则 det(A) 对变数 x 的微分为割裂元素微分的行列式值之和。

$$\begin{align}
let\ |A| &= \begin{vmatrix} a(x) & b(x) & c(x) \\
                           d(x) & e(x) & f(x) \\
                           g(x) & h(x) & i(x) \end{vmatrix}
\\
\frac{d|A|}{dx} &= \begin{vmatrix} 
                       \frac{da(x)}{dx} & \frac{db(x)}{dx} & \frac{dc(x)}{dx} \\
                       d(x) & e(x) & f(x) \\
                       g(x) & h(x) & i(x) \end{vmatrix} +
                   \begin{vmatrix} 
                       a(x) & b(x) & c(x) \\
                       \frac{dd(x)}{dx} & \frac{de(x)}{dx} & \frac{df(x)}{dx} \\
                       g(x) & h(x) & i(x) \end{vmatrix} +
                   \begin{vmatrix} 
                       a(x) & b(x) & c(x) \\
                       d(x) & e(x) & f(x) \\
                       \frac{dg(x)}{dx} & \frac{dh(x)}{dx} & \frac{di(x)}{dx} \end{vmatrix}
\end{align}$$

### 4-14
行列式值里面的元素可以另外视为一个矩阵做为行列式值的运算。

In [29]:
G = np.array([[1, 2, 7, 8, 5],
              [4, 9, 6, 4, 3],
              [0, 0, 1, 2, 3],
              [0, 0, 4, 5, 7],
              [0, 0, 8, 1, 6]])
determinant(G)

-21.0

In [30]:
determinant(G[:2, :2]) * determinant(G[2:, 2:])

-21.000000000000032

### 4-15
若 A 与 B 为 n 阶方阵，则：

$$
\begin{vmatrix} A & B \\
                B & A \end{vmatrix} = |A + B|\cdot |A - B|
$$

In [31]:
H = np.array([[1, 2, 7, 8],
              [4, 9, 6, 4],
              [7, 8, 1, 2],
              [6, 4, 4, 9]])
determinant(H)

-168.00000000000023

In [32]:
determinant(H[:2, :2] + H[2:, :2]) * determinant(H[:2, :2] - H[2:, :2])

-167.99999999999937

### 4-16
计算一个矩阵是由多少个不同的方向向量所组成，该量又称为 `秩` (rank).

In [33]:
np.linalg.matrix_rank(A)

3