> 关键词：线性代数 / 矩阵 / 基本定义

矩阵对于算法就如同人对于食物般的关系，已经到了密不可分的状态了，在神经网络里，矩阵代表了每层神经元之间的链接，在集成算法里，矩阵记录了每次分类器更新的残差，在马可夫链里，矩阵表示了不同状态下的条件转移概率，矩阵的重要性已经是不言自明了。除了上集说到的方阵，子矩阵，对角矩阵，与单位矩阵之外，接着要进一步介绍一些常用且方便的矩阵，包含了以下几种矩阵类型：
+ 纯量矩阵
+ 三角矩阵
+ 共轭矩阵
+ 对称矩阵
+ 正交矩阵

当然矩阵的类型远不止如此，而这几种矩阵在了解的时候不需要太多先验知识，因此才能在一开始率先登场！

In [1]:
import numpy as np

# 矩阵基本定义
本节主要介绍不同矩阵名称背后的定义，并直接使用代码来计算我们希望看到的结果。

$$
A = 
\begin{bmatrix} a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
                a_{21} & a_{22} & a_{23} & \cdots & a_{2n} \\
                ...  & ...  & ...  & \quad  & ... \\
                a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mn}\end{bmatrix}
= \big[a_{ij}\big]
$$

$[\ \cdot\ ]$ 中的 $a_{ij}$ 称为矩阵的元素，可以是数字，函数，实数，复数。在 python 代码中的`numpy`模块几乎可以说是数值计算的唯一选择。

In [2]:
A = np.random.randint(0, 10, 72).reshape(9, 8)
print(A)

[[5 4 5 8 5 7 0 7]
 [5 6 4 0 9 8 6 5]
 [1 2 9 6 7 7 3 5]
 [3 4 7 8 4 6 9 2]
 [4 8 1 3 5 4 8 4]
 [5 1 5 7 3 9 9 8]
 [0 8 4 1 6 9 3 2]
 [4 3 0 3 6 4 5 9]
 [2 8 6 3 5 5 3 4]]


## 11. 纯量矩阵 - Scalar matrix
在对角矩阵中，主对角线上的元素皆为某一常数 C 时，则称之为纯量矩阵。

In [20]:
c = 5
np.diag([c, c, c])

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

## 12. 上三角矩阵 - Upper triangular matrix
在方阵的前提下，主对角线以下元素皆为 0 时，则称之为上三角矩阵。

In [21]:
np.triu(A)

array([[5, 4, 5, 8, 5, 7, 0, 7],
       [0, 6, 4, 0, 9, 8, 6, 5],
       [0, 0, 9, 6, 7, 7, 3, 5],
       [0, 0, 0, 8, 4, 6, 9, 2],
       [0, 0, 0, 0, 5, 4, 8, 4],
       [0, 0, 0, 0, 0, 9, 9, 8],
       [0, 0, 0, 0, 0, 0, 3, 2],
       [0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0]])

## 13. 下三角矩阵 - Lower triangular matrix
在方阵的前提下，主对角线以上元素皆为 0 时，则称之为下三角矩阵。

In [22]:
np.tril(A)

array([[5, 0, 0, 0, 0, 0, 0, 0],
       [5, 6, 0, 0, 0, 0, 0, 0],
       [1, 2, 9, 0, 0, 0, 0, 0],
       [3, 4, 7, 8, 0, 0, 0, 0],
       [4, 8, 1, 3, 5, 0, 0, 0],
       [5, 1, 5, 7, 3, 9, 0, 0],
       [0, 8, 4, 1, 6, 9, 3, 0],
       [4, 3, 0, 3, 6, 4, 5, 9],
       [2, 8, 6, 3, 5, 5, 3, 4]])

## 14. 共轭矩阵 - Conjugate matrix
把 A 矩阵的元素皆取共轭复数后，该新的矩阵为 A 矩阵的共轭矩阵，以 $\bar{A}$ 表示。

In [23]:
np.conj(B)

array([[1.-1.j, 2.+1.j],
       [3.+2.j, 4.-5.j]])

## 15. 转置矩阵 - Transpose matrix
把 A 矩阵中的行列编号互换，元素不变，只变位置后的结果称为 A 矩阵的转置矩阵，以 $A^T$ 表示。

In [24]:
A.T

array([[5, 5, 1, 3, 4, 5, 0, 4, 2],
       [4, 6, 2, 4, 8, 1, 8, 3, 8],
       [5, 4, 9, 7, 1, 5, 4, 0, 6],
       [8, 0, 6, 8, 3, 7, 1, 3, 3],
       [5, 9, 7, 4, 5, 3, 6, 6, 5],
       [7, 8, 7, 6, 4, 9, 9, 4, 5],
       [0, 6, 3, 9, 8, 9, 3, 5, 3],
       [7, 5, 5, 2, 4, 8, 2, 9, 4]])

## 16. 共轭转置矩阵 - Conjugate transpose matrix
把 A 矩阵的元素皆取共轭复数后，再取转置；或将 A 矩阵的元素先取转置后，再取共轭复数，所得到的新矩阵即为共轭转置矩阵，以 $A^\star$ 表示。

In [25]:
np.matrix(B).H

matrix([[1.-1.j, 3.+2.j],
        [2.+1.j, 4.-5.j]])

In [26]:
np.conj(B).T

array([[1.-1.j, 3.+2.j],
       [2.+1.j, 4.-5.j]])

## 17. 对称矩阵 - Symmetrix matrix
在方阵的前提下，如果矩阵 A 的转置等于 A 本身，称之为对称矩阵。

In [27]:
def symmetrixIO(mat):
    return np.sum(mat != mat.T) == 0

In [28]:
symmetrixIO(C)

False

## 18. 反对称矩阵 - Skew symmetrix matrix
在方阵的前提下，如果矩阵 A 的转置矩阵恰为 A 的相反矩阵 -A，则称之为反对称矩阵。

In [29]:
def skew_symmetrixIO(mat):
    return np.sum(-mat != mat.T) == 0

In [30]:
skew_symmetrixIO(np.array([[ 0, 2,  5],
                           [-2, 0, -7],
                           [-5, 7,  0]]))

True

## 19. 厄米特矩阵 - Hermitian matrix
在方阵的前提下，矩阵 A 的共轭转置矩阵恰好等于原矩阵 A，则称之为厄米特矩阵。

In [31]:
def hermitianIO(mat):
    return np.sum(mat != np.conj(mat).T) == 0

In [32]:
hermitianIO(np.array([[    1, 1+1.j,   5],
                      [1-1.j,     2, 1.j],
                      [    5,  -1.j,   7]]))

True

---

In [1]:
from linalg import *

## 20. 正交矩阵 - Orthogonal matrix
正交的意思就是指两个向量彼此互相垂直，而正交矩阵则进一步把垂直的概念拓展到矩阵中，矩阵里的每一个行和列向量必须彼此互相垂直，而且向量长度是1的情况下，才称之为正交矩阵。总结矩阵的规则后，我们得到在方阵的前提下，满足以下条件则称之为正交矩阵：
1. $A^T = A^{-1}$
2. $A^TA = AA^T = \mathbf{I}$
3. $|A|\pm 1$

因此很明显的，一个正交矩阵必定是个方阵，而这一系列的条件判断同样可以被写成一个函数用来检测矩阵是否正交。

In [5]:
def orthogonalIO(mat, decimal=4):
    # A^T = A^(-1)
    cond1 = np.sum(np.round(mat.T, decimal) !=
                   np.round(inverse(mat), decimal)) == 0
    # A^T . A = A . A^T
    cond2 = np.sum(np.round(np.dot(mat.T, mat), decimal) !=
                   np.round(np.dot(mat, mat.T), decimal)) == 0
    # |A| = +-1
    cond3 = np.round(np.abs(determinant(mat)), decimal) == 1
    return np.sum([cond1, cond2, cond3]) == 3

In [6]:
B = np.array([[-0.23939017,  0.58743526, -0.77305379],
              [ 0.81921268, -0.30515101, -0.48556508],
              [-0.52113619, -0.74953498, -0.40818426]])

In [7]:
orthogonalIO(B, decimal=4)

True

为了更深入了解矩阵的底层运算，行列式值和逆矩阵都用的是我们自定义的函数，如果想看具体实现方法，欢迎持续关注发布的文章！在这个函数中我们首先就遇到了一个很简单的理论与实际代码之间的差异，那就是小数点近似问题。由于任意行列向量必须是单位向量，常常在实际情况是一个近似的结果，因此在检测正交与否的时候也必须采用近似的方式操作。