> 关键词：线性代数 / 矩阵 / 运算

今天小编将详细介绍矩阵的运算规则与数学符号应用在矩阵上的含义，如同算数字的加减法需要了解计算公式的规则一样，矩阵的运算虽然与单纯数字运算相似，但其细节的相异处还需要多加注意。另外，矩阵计算有些时候手算和代码算的规则是有些差异的，这也容易造成算法在实际部署时的 BUG，接下来的矩阵操作介绍，小编将完全站在编程的角度去重新阐述线性代数的理论知识！

# 矩阵的基本性质
回顾一下一个矩阵的具体写法与符号定义：

$$
A = 
\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\
                a_{21} & a_{22} & \cdots & a_{2n} \\
                ...  & ...  & \quad  & ... \\
                a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}
= \begin{bmatrix}a_{ij}\end{bmatrix}
$$

$[\ \cdot\ ]$ 中的 $a_{ij}$ 称为矩阵的元素，可以是数字，函数，实数，复数。在 python 代码中的`numpy`模块几乎可以说是数值计算的唯一选择。

In [1]:
import numpy as np
from linalg import *

如果还没安装过`numpy`，可以使用下面指令在终端快速安装。

```shell
pip install numpy
```

如果想获得`Code.linalg`里面的代码，欢迎扫码进群！

## 1. 矩阵的相等
如果 A 与 B 两个矩阵的阶数相等，所对应的元素也都相等，则称 A 与 B 矩阵相等。

$$
A_{m\times n} = B_{m\times n}\quad\rightarrow\quad (A)_{ij} = (B)_{ij}
$$

## 2. 加减法
如果两个矩阵的阶数都相等，则加减法即为对应位置的元素相加减。

In [2]:
A = np.random.randint(0, 5, 6).reshape(2, 3)
B = np.random.randint(0, 5, 6).reshape(2, 3)
C = np.random.randint(0, 8, 6).reshape(3, 2)
print(A, '\n\n', B, '\n\n', C)

[[0 2 1]
 [1 3 4]] 

 [[0 4 1]
 [1 2 2]] 

 [[0 2]
 [3 1]
 [1 5]]


In [3]:
print(A + B)

[[0 6 2]
 [2 5 6]]


## 3. 纯量与矩阵的乘积
如果 A 为矩阵而 k 为常数，相乘的结果即为每个 A 内的元素都乘以 k。

In [4]:
10 * A

array([[ 0, 20, 10],
       [10, 30, 40]])

## 4. 矩阵的乘法
如果两个矩阵的 `行数` 与另一个矩阵的 `列数` 相等，矩阵乘法才可行，此操作又称为内积。

$$
C_{m\times l} = A_{m\times n} \cdot B_{n\times l}
\\
(C)_{ij} = \sum_{k=1}^n(A)_{ik}(B)_{kj}
$$

In [5]:
np.dot(A, A.T)

array([[ 5, 10],
       [10, 26]])

有些在数字上通用的乘法规则，在矩阵中则无效，如下实例：
#### -- 交换律不成立
成立条件：
1. A 与 B 都是 n 阶对角矩阵
2. A 或 B 中有一个为纯量矩阵（包含单位矩阵）

#### -- 消去律不成立
如果 A 与 B 皆为 n 阶方阵，AB = AC 不表示 B = C，成立条件：
+ $A^{-1}$ 存在。

#### -- 为 0 条件
如果 AB = 0，不恒表示 A = 0 或是 B = 0。成立条件：
+ 当 $A^{-1}$ 存在，则 B = 0
+ 当 $B^{-1}$ 存在，则 A = 0

#### -- 结合律成立
+ $A(BC) = (AB)C$，其中 $A_{m\times n}, B_{n\times l}, C_{l\times p}$
+ $(A + B)C = AC + BC$
+ $(A + B)(C + D) = AC + BC + AD + BD$
+ $(A + B)^2 = (A + B)(A + B) = A^2 + BA + AB + B^2$

## 5. 转置矩阵的性质
转置操作从二维矩阵的角度看，就是把矩阵沿着对角线做一个 180 度的翻转，长宽的尺寸维度也因此跟着变化。如果是高维张量的转置操作，则可以理解成是不同维度的值调换了位置，更多细节将在后面几个章节细说！

+ $(A^T)^T = A$

In [6]:
A == A.T.T

array([[ True,  True,  True],
       [ True,  True,  True]])

+ $(A + B)^T = A^T + B^T$

In [7]:
(A + B).T == A.T + B.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

+ 如果 k 是常数，$(kA)^T = kA^T$

In [8]:
(10 * A).T == 10 * A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

+ $(ABC)^T = C^TB^TA^T$

证明：$(AB)^T$ 矩阵中第 i 列第 j 行未知的元素为：

$$\begin{align}
\big((AB)^T\big)_{ij} = (AB)_{ji} &= \sum_{k=1}^n(A)_{jk}(B)_{ki}
\\
&= \sum_{k=1}^n(B)_{ki}(A)_{jk}
\\
&= \sum_{k=1}^n(B^T)_{ik}(A^T)_{kj} = (B^TA^T)_{ij}
\end{align}$$

得证。

In [9]:
np.dot(A, C).dot(B).T == np.dot(B.T, C.T).dot(A.T)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## 6. 共轭转置矩阵的性质
共轭转置操作就跟名字起的顺序一样，先做共轭再做转置，数学上计作 上标$\star$。

+ $(A^\star)^\star = A$

In [10]:
conj_T(conj_T(A)) == A

array([[ True,  True,  True],
       [ True,  True,  True]])

+ $(A + B)^\star = A^\star + B^\star$

In [11]:
conj_T(A + B) == conj_T(A) + conj_T(B)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

+ 如果 k 是常数，$(kA)^\star = \bar{k}A^\star$

In [12]:
conj_T(10 * A) == 10 * conj_T(A)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

+ $(ABC)^\star = C^\star B^\star A^\star$

In [13]:
conj_T(np.dot(A, C).dot(B)) == np.dot(conj_T(B), conj_T(C)).dot(conj_T(A))

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## 7. 对称矩阵与反对称矩阵的性质
如果 A 是 n 阶方阵，则有：
+ $AA^T$ 与 $A^TA$ 为 `对称矩阵`

证明：$(AA^T)^T = (A^T)^TA^T = AA^T$，且 $(A^TA)^T = A^T(A^T)^T = A^TA$

In [14]:
np.dot(A, A.T)

array([[ 5, 10],
       [10, 26]])

In [15]:
np.dot(A.T, A)

array([[ 1,  3,  4],
       [ 3, 13, 14],
       [ 4, 14, 17]])

+ $(A + A^T)^T$ 为 `对称矩阵`

证明：$(A + A^T)^T = A^T + (A^T)^T = A^T + A = A + A^T$

In [16]:
D = np.random.randint(0, 10, 9).reshape(3, 3)
D    # random square matrix

array([[1, 4, 6],
       [8, 2, 2],
       [8, 3, 0]])

In [17]:
(D + D.T).T

array([[ 2, 12, 14],
       [12,  4,  5],
       [14,  5,  0]])

+ $A - A^T$ 为 `反对称矩阵`

证明：$(A - A^T)^T = A^T - (A^T)^T = A^T - A = -(A - A^T)^T$

In [18]:
(D - D.T).T

array([[ 0,  4,  2],
       [-4,  0,  1],
       [-2, -1,  0]])

+ 任何 n 阶实数方阵必定可以表示成 `对称矩阵` 与 `反对称矩阵` 的和：$A = \frac{1}{2}(A + A^T) + \frac{1}{2}(A - A^T)$

In [19]:
0.5 * (D + D.T) + 0.5 * (D - D.T) == D

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 8. Trace 的性质
+ $tr(A \pm B) = tr(A) \pm tr(B)$

证明：$tr(A\pm B) = \sum_{i=1}^n \Big((A)_{ii} \pm (B)_{ii}\Big) = \sum_{i=1}^n (A)_{ii} \pm \sum_{i=1}^n(B)_{ii} = tr(A) \pm tr(B)$

In [20]:
np.trace(A + B) == np.trace(A) + np.trace(B)

True

+ 当 k 是个常数，$tr(kA) = k\cdot tr(A)$

In [21]:
np.trace(10 * A) == 10 * np.trace(A)

True

+ $tr(AB) = tr(BA)$

证明：$tr(AB) = \sum_{i=1}^n(AB)_{ii} = \sum_{i=1}^n\sum_{j=1}^n(A)_{ij}(B)_{ji} = \sum_{j=1}^n\sum_{i=1}^n(B)_{ji}(A)_{ij} = \sum_{j=1}^n(BA)_{jj}$

In [22]:
np.trace(np.dot(A, C)) == np.trace(np.dot(C, A))

True

+ 若 $P^{-1}$ 存在，$P^{-1}AP = B$，$tr(A) = tr(B)$

证明：$tr(B) = tr(P^{-1}AP) = tr(PP^{-1}A) = tr(A)$