> 关键词：线性代数 / 伴随 / 反矩阵 / 基础数学
>
> 再复杂的算法，也逃脱不了线性代数的掌心，AI 算法辞典帮你复习矩阵计算！

矩阵计算是世界上所有算法的祖宗，今天小编就来为读者们好好复习两个知识点：`伴随矩阵 (adjoint matrix)` 与 `逆矩阵 (inverse matrix)`！算法推导的过程中，最常遇到的操作之一就是对一个矩阵求逆，通常数值计算的工具，例如 `numpy`，都提供好了直接调用的函数给我们使用，但用着用着就难免忘了逆矩阵到底对本来的矩阵做了什么操作，因此接下来就要刨开AI的地基来一探究竟！

In [1]:
import numpy as np
from linalg import *

# 伴随矩阵 Adjoint Matrix
定义一个 A 矩阵：

$$
A = 
\begin{bmatrix} a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
                a_{21} & a_{22} & a_{23} & \cdots & a_{2n} \\
                ...  & ...  & ...  & \quad  & ... \\
                a_{n1} & a_{n2} & a_{n3} & \cdots & a_{nn}\end{bmatrix}
$$

若 $C_{ij}$ 表 $a_{ij}$ 的 cofactor (余因子)，则定义 A 的伴随矩阵如下：

$$
adj\ A = 
\begin{bmatrix} C_{11} & C_{12} & C_{13} & \cdots & C_{1n} \\
                C_{21} & C_{22} & C_{23} & \cdots & C_{2n} \\
                ...  & ...  & ...  & \quad  & ... \\
                C_{n1} & C_{n2} & C_{n3} & \cdots & C_{nn}\end{bmatrix}^{\ T} = \mathbf{C}^T
$$

In [2]:
A = np.array([[3, 2, 5],
              [4, 1, 7],
              [9, 8, 3]])

In [3]:
def adjoint(mat):
    temp = np.zeros(mat.shape)
    for row in range(mat.shape[0]):
        for col in range(mat.shape[1]):
            temp[row, col] = cofactor(mat, row, col)
    return temp.T

In [4]:
adjoint(A)

array([[-53.,  34.,   9.],
       [ 51., -36.,  -1.],
       [ 23.,  -6.,  -5.]])

## 1. 伴随矩阵性质

### 1-1
$$A\cdot adj\ A = |A|\ \mathbf{I}\quad \quad \dots A\ 为\ n\ 阶方阵$$

证明：令 $A_{ij}$ 表 A 矩阵第 i 列，第 j 行位置的元素，且 $adj\ A = \mathbf{C}^T$ 如上所述，则：

$$
(A\cdot adj\ A)_{ij} = \sum_{k=1}^n A_{ik}C^T_{kj} = \sum_{k=1}^nA_{ik}C_{jk}
$$

用 Laplace 行列式展开法
+ 当 $i=j$ 时，$(A\cdot adj\ A)_{ij} = \sum_{k=1}^nA_{ik}C_{ik} = |A|$
+ 当 $i\neq j$ 时，$(A\cdot adj\ A)_{ij} = 0$

故得：
$$
A\cdot adj\ A = \begin{bmatrix} |A| & 0 & 0 & \cdots & 0 \\
                0 & |A| & 0 & \cdots & 0 \\
                ...  & ...  & ...  & \quad  & ... \\
                0 & 0 & 0 & \cdots & |A|\end{bmatrix}
                = |A|\ \mathbf{I}
$$

In [5]:
np.round(np.dot(A, adjoint(A)), decimals=5)

array([[58., -0.,  0.],
       [ 0., 58.,  0.],
       [ 0., -0., 58.]])

In [6]:
determinant(A)

58.00000000000004

### 1-2
$$
|adj\ A| = |A|^{n-1}
$$

证明：因为 $A\cdot adj\ A = |A| \mathbf{I}$，所以得：

$$\begin{align}
|A\cdot adj\ A| &= \big||A|\ \mathbf{I}\big|
\\
|A|\cdot |adj\ A| &= |A|^n \rightarrow |adj\ A| = |A|^{n-1}
\end{align}$$

p.s. n 表示矩阵的阶数。

In [7]:
determinant(adjoint(A))

3363.9999999999973

In [8]:
determinant(A) ** 2

3364.000000000005

### 1-3
$$
adj(kA) = k^{n-1}adj\ A\quad\quad \dots k\ 为常数，A\ 为\ n\ 阶方阵
$$

证明：

$$\begin{align}
因\ A\cdot adj\ A &= |A|\ \mathbf{I}\quad \rightarrow A^{-1} = \frac{adj\ A}{|A|}\quad \dots (1)
\\
(kA)\cdot adj(kA) &= |kA|\mathbf{I} = k^n|A|\ \mathbf{I}
\\
故\ adj(kA) &= A^{-1}k^{n-1}|A|\ \mathbf{I}
\\
\end{align}$$

把 `(1)` 代入上式得：$adj(kA) = k^{n-1}adj\ A$

In [9]:
adjoint(13 * A)

array([[-8957.,  5746.,  1521.],
       [ 8619., -6084.,  -169.],
       [ 3887., -1014.,  -845.]])

In [10]:
(13 ** 2) * adjoint(A)

array([[-8957.,  5746.,  1521.],
       [ 8619., -6084.,  -169.],
       [ 3887., -1014.,  -845.]])

### 1-4
$$
adj(adj\ A) = |A|^{n-2}A\quad\quad \dots A\ 为\ n\ 阶方阵
$$

证明：

$$
A\cdot adj\ A = |A|\ \mathbf{I}\rightarrow A^{-1} = \frac{adj\ A}{|A|}\quad \dots (1)
\\
\begin{align}
(adj\ A)adj(adj\ A) &= |adj\ A|\ \mathbf{I} = |A|^{n-1}\mathbf{I}
\\
adj(adj\ A) &= (adj\ A)^{-1}|A|^{n-1}\mathbf{I}\quad\quad \dots (2)
\end{align}$$

把 `(1)` 带入 `(2)` 得：

$$
adj(adj\ A) = \frac{A}{|A|}|A|^{n-1}\ \mathbf{I} = |A|^{n-2}A
$$

In [11]:
adjoint(adjoint(A))

array([[174., 116., 290.],
       [232.,  58., 406.],
       [522., 464., 174.]])

In [12]:
determinant(A) ** (3 - 2) * A

array([[174., 116., 290.],
       [232.,  58., 406.],
       [522., 464., 174.]])

# 逆矩阵 Inverse Matrix
$$
A^{-1} = \frac{adj\ A}{|A|}
$$

当以下条件被满足：
1. A 为 n 阶方阵
3. $det(A) \neq 0$
3. $AA^{-1} = A^{-1}A = I$

证明：

$$
A\cdot adj\ A = |A|\ \mathbf{I}
\\
A\frac{adj\ A}{|A|} = \mathbf{I}
\\
故得：A^{-1} = \frac{adj\ A}{|A|}
$$

In [13]:
def inverse(mat):
    return adjoint(mat) / determinant(mat)

In [14]:
inverse(A)

array([[-0.9137931 ,  0.5862069 ,  0.15517241],
       [ 0.87931034, -0.62068966, -0.01724138],
       [ 0.39655172, -0.10344828, -0.0862069 ]])

In [15]:
# 用 numpy 提供的 API 重复验证结果
np.linalg.inv(A) 

array([[-0.9137931 ,  0.5862069 ,  0.15517241],
       [ 0.87931034, -0.62068966, -0.01724138],
       [ 0.39655172, -0.10344828, -0.0862069 ]])

证明结果相同。

## 2. 逆矩阵性质

### 2-1
$$
|A^{-1}| = \frac{1}{|A|}
$$

证明：

$$
AA^{-1} = \mathbf{I}
\\
|AA^{-1}| = |\mathbf{I}| = 1
\\
|A||A^{-1}| = 1
故\ |A^{-1}| = \frac{1}{|A|}
$$

In [16]:
determinant(inverse(A))

0.01724137931034483

In [17]:
1 / determinant(A)

0.017241379310344813

### 2-2
$$
A = \frac{adj\ A^{-1}}{|A^{-1}|}
$$

证明：

$$
A\cdot adj\ A = |A|\ \mathbf{I}
\\
A^{-1}adj\ A^{-1} = |A^{-1}|\ \mathbf{I}
\\
A^{-1}\frac{adj\ A^{-1}}{|A^{-1}|} = \mathbf{I}
\\
故\ A = \frac{adj\ A^{-1}}{|A^{-1}|}
$$

In [18]:
adjoint(inverse(A)) / determinant(inverse(A))

array([[3., 2., 5.],
       [4., 1., 7.],
       [9., 8., 3.]])

In [19]:
A

array([[3, 2, 5],
       [4, 1, 7],
       [9, 8, 3]])

### 2-3
如果 A 是可逆矩阵，则 $adj\ A$ 同为可逆矩阵。

证明：如果 A 为可逆矩阵，表示 $|A| \neq 0$，且因为

$$
A\cdot adj\ A = |A|\ \mathbf{I}
\\
|adj\ A| = |A|^{n-1} \neq 0
$$

得证 $adj\ A$ 为可逆矩阵。

### 2-4
$$
(AB)^{-1} = B^{-1}A^{-1}\quad\quad\dots |A|\neq 0,\ |B|\neq 0
$$

证明：

$$\begin{align}
(AB)(AB)^{-1} &= \mathbf{I}
\\
B(AB)^{-1} &= A^{-1}
\\
(AB)^{-1} &= B^{-1}A^{-1}
\end{align}$$

In [20]:
B = np.array([[4, 2, 7],
              [3, 8, 9],
              [1, 4, 2]])

In [21]:
inverse(np.dot(A, B))

array([[-0.52848576,  0.49325337,  0.00524738],
       [ 0.1697901 , -0.05847076, -0.03785607],
       [ 0.12293853, -0.1814093 ,  0.02998501]])

In [22]:
np.dot(inverse(B), inverse(A))

array([[-0.52848576,  0.49325337,  0.00524738],
       [ 0.1697901 , -0.05847076, -0.03785607],
       [ 0.12293853, -0.1814093 ,  0.02998501]])

同理 $(ABC)^{-1} = C^{-1}B^{-1}A^{-1}$.

### 2-5
$$
(A^T)^{-1} = (A^{-1})^T
$$

证明：

$$\begin{align}
AA^{-1} &= \mathbf{I}
\\
(AA^{-1})^T &= \mathbf{I}^T = \mathbf{I}
\\
(A^{-1})^TA^T &= \mathbf{I}
\\
故\ (A^T)^{-1} &= (A^{-1})^T
\end{align}$$

In [23]:
inverse(A.T)

array([[-0.9137931 ,  0.87931034,  0.39655172],
       [ 0.5862069 , -0.62068966, -0.10344828],
       [ 0.15517241, -0.01724138, -0.0862069 ]])

In [24]:
inverse(A).T

array([[-0.9137931 ,  0.87931034,  0.39655172],
       [ 0.5862069 , -0.62068966, -0.10344828],
       [ 0.15517241, -0.01724138, -0.0862069 ]])

### 2-6
$$
(A^{-1})^{-1} = A
$$

证明：

$$\begin{align}
AA^{-1} &= \mathbf{I}
\\
(AA^{-1})^{-1} &= \mathbf{I}^{-1} = \mathbf{I}
\\
(A^{-1})^{-1}A^{-1} &= \mathbf{I}
\end{align}$$

与上式比较则得：$(A^{-1})^{-1} = A$.

In [25]:
inverse(inverse(A))

array([[3., 2., 5.],
       [4., 1., 7.],
       [9., 8., 3.]])

In [26]:
A

array([[3, 2, 5],
       [4, 1, 7],
       [9, 8, 3]])

### 2-7
如果 k 为常数，A 为 n 阶方阵，且 $|A|\neq 0$，则：

$$
|kA^{-1}| = \frac{k^n}{|A|}
$$

证明：

$$
|kA^{-1}| = k^n |A^{-1}| = \frac{k^n}{|A|}
$$

In [27]:
determinant(7 * inverse(A))

5.913793103448269

In [28]:
(7 ** 3) / determinant(A)

5.913793103448271

### 2-8
如果 A 是 `对角矩阵`，则 $A{-1}$ 一样是对角矩阵，且对角线上元素恰好是 A 对角线上元素得倒数。

In [29]:
C = np.diag([4, 2, 5])
C

array([[4, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [30]:
inverse(C)

array([[ 0.25, -0.  ,  0.  ],
       [-0.  ,  0.5 , -0.  ],
       [ 0.  , -0.  ,  0.2 ]])